// <auto-generated />
using financas.repository;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage;
using Microsoft.EntityFrameworkCore.Storage.Internal;
using System;

namespace financas.repository.Migrations
{
    [DbContext(typeof(FinancasContext))]
    partial class FinancasContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("MySql:ValueGenerationStrategy", MySqlValueGenerationStrategy.IdentityColumn)
                .HasAnnotation("ProductVersion", "2.0.1-rtm-125");

            modelBuilder.Entity("financas.domain.Despesa", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd();

                    b.Property<int>("GrupoDespesaId");

                    b.Property<string>("data");

                    b.Property<string>("nome");

                    b.Property<long>("numDoc");

                    b.Property<double>("valor");

                    b.HasKey("id");

                    b.HasIndex("GrupoDespesaId");

                    b.ToTable("Despesas");
                });

            modelBuilder.Entity("financas.domain.GrupoDespesa", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("nomeGrupo");

                    b.HasKey("Id");

                    b.ToTable("GrupoDespesas");
                });

            modelBuilder.Entity("financas.domain.Despesa", b =>
                {
                    b.HasOne("financas.domain.GrupoDespesa", "grupoDespesas")
                        .WithMany("Despesas")
                        .HasForeignKey("GrupoDespesaId")
                        .OnDelete(DeleteBehavior.Cascade);
                });
#pragma warning restore 612, 618
        }
    }
}
